# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tap/proto/tap.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'tap/proto/tap.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13tap/proto/tap.proto\x12\x06tap.v1\"\x91\x01\n\x12ThermodynamicState\x12\x1d\n\x15ground_state_verified\x18\x01 \x01(\x08\x12 \n\x18staked_energy_collateral\x18\x02 \x01(\x05\x12\x1f\n\x17\x63umulative_shear_stress\x18\x03 \x01(\x02\x12\x19\n\x11\x66ree_volume_ratio\x18\x04 \x01(\x02\"\x92\x01\n\x06Header\x12\x13\n\x0btap_version\x18\x01 \x01(\t\x12\x11\n\tsender_id\x18\x02 \x01(\t\x12\x13\n\x0breceiver_id\x18\x03 \x01(\t\x12\x12\n\nsession_id\x18\x04 \x01(\t\x12\x37\n\x13thermodynamic_state\x18\x05 \x01(\x0b\x32\x1a.tap.v1.ThermodynamicState\"\\\n\x0fResourceRequest\x12\x1a\n\x12max_context_tokens\x18\x01 \x01(\x05\x12\x19\n\x11\x63ompute_precision\x18\x02 \x01(\t\x12\x12\n\ntimeout_ms\x18\x03 \x01(\x05\"\xad\x01\n\x0fProposalRequest\x12\x1e\n\x06header\x18\x01 \x01(\x0b\x32\x0e.tap.v1.Header\x12\x15\n\rcontract_type\x18\x02 \x01(\t\x12\x31\n\x10resource_request\x18\x03 \x01(\x0b\x32\x17.tap.v1.ResourceRequest\x12\x0f\n\x07payload\x18\x04 \x01(\x0c\x12\x1f\n\x17payload_utility_density\x18\x05 \x01(\x02\"\x82\x01\n\x10ProposalResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\x12\x1b\n\x13\x63ollateral_returned\x18\x03 \x01(\x05\x12\x14\n\x0c\x65\x61rned_yield\x18\x04 \x01(\x05\x12\x1b\n\x13\x63urrent_shear_score\x18\x05 \x01(\x02\x32Q\n\nTAPService\x12\x43\n\x0eSubmitProposal\x12\x17.tap.v1.ProposalRequest\x1a\x18.tap.v1.ProposalResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tap.proto.tap_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_THERMODYNAMICSTATE']._serialized_start=32
  _globals['_THERMODYNAMICSTATE']._serialized_end=177
  _globals['_HEADER']._serialized_start=180
  _globals['_HEADER']._serialized_end=326
  _globals['_RESOURCEREQUEST']._serialized_start=328
  _globals['_RESOURCEREQUEST']._serialized_end=420
  _globals['_PROPOSALREQUEST']._serialized_start=423
  _globals['_PROPOSALREQUEST']._serialized_end=596
  _globals['_PROPOSALRESPONSE']._serialized_start=599
  _globals['_PROPOSALRESPONSE']._serialized_end=729
  _globals['_TAPSERVICE']._serialized_start=731
  _globals['_TAPSERVICE']._serialized_end=812
# @@protoc_insertion_point(module_scope)
